### ISSUE TITLE
Hide Guest Wifi

### ISSUE THREAD

**Issue by GoProAndy** [andig/homebridge-fritz#25] opened 2017-08-31 22:39 UTC
Hi Andreas,

is it possible to block the WiFi button to get added to Kit?

thanks
Andreas

**Comment by ghost** [comment] 2017-09-03 11:14
Looking also for an option to filter devices like its done in the homebridge-homematic plugin

**Comment by andig** [comment] 2017-09-03 11:55
I'll take a look, thanks for the reference to the homematic plugin, that'll make it easier.

**Comment by ghost** [comment] 2017-09-03 20:42
IF you block the device itself from being update inside the fritz box setting is a work around. The toggle in the bottom page of the device in the smart home tab inside fritz box webinterface

**Comment by andig** [comment] 2017-09-04 11:10
Duplicate of #22

**Comment by andig** [comment] 2017-09-05 04:46
Please check if 7487a6a1209c131b312f3ddabd371cf68018e235 fixes your issue.

**Comment by ghost** [comment] 2017-09-05 18:15
i put the new files inside /usr/lib/node_modules/homebridge-fritz and added the       "hide": ["wifi"], in my config.json but the wifi is still appearing

**Comment by andig** [comment] 2017-09-05 19:48
Did you restart homebridge? Is homebridge globally installed?

**Comment by andig** [comment] 2017-09-06 08:48
Please try again- I've corrected a stupid bug. You could also try installing globally from git:

    npm install -g https://github.com/andig/homebridge-fritz

This will install the current master branch.

**Comment by ghost** [comment] 2017-09-06 09:50
Working perfectly wifi and with AIN

Thanks for the fast feature update!

**Comment by b2un0** [comment] 2017-09-06 10:21
Now it works, thank you @andig !

**Closed as completed** 2017-09-06 10:43 UTC
Labels: enhancement

**Comment by GoProAndy** [comment] 2017-09-06 20:19
Hey thanks - works perfect!
