### ISSUE TITLE
Manual changes not updated

### ISSUE THREAD

**Issue by jngmrks** [andig/homebridge-fritz#14] opened 2016-12-03 01:52 UTC
When the thermostats/switches/temps are changed in value by change them on the devices or by time circuit the new values are not updated in HomeKit. HomeKit request the values when HomeKit starts or when values change in HomeKit. This must and seems not to be possible immediately, the update interval are sufficient. For now the Home-App need to be restarted on every change.

For example, you turn a switch on via FritzFon. In Homekit you see the switch is off. To turn it really off it must be switched on and off. (or restart the Home-App and see its on then turn it off).
Or you see the thermostat temperatur of 22°, the time circuit change it to 16°. You see 22° until you restart the Home-App.

**Comment by jngmrks** [comment] 2016-12-03 14:20
Found this:

> justme-1968: set characteristic.eventEnabled = true; (for example in the onRegister callback). and then if you receive the event call characteristic.updateValue(value, null); with the value you received from your device. this will push the new value to homekit and all listening apps. works perfectly.

on https://github.com/nfarina/homebridge/issues/85

**Comment by andig** [comment] 2017-06-22 13:17
> When the thermostats/switches/temps are changed in value by change them on the devices or by time circuit the new values are not updated in HomeKit. 

I'm not sure I follow. When you look here https://github.com/andig/homebridge-fritz/blob/master/index.js#L226 you'll see that we're regularly polling the accessories and here https://github.com/andig/homebridge-fritz/blob/master/index.js#L252 updating it's value. 

Are you saying that this update doesn't work unless something like https://github.com/nfarina/homebridge/issues/85 is implemented?

**Comment by jngmrks** [comment] 2017-06-24 18:58
>Are you saying that this update doesn't work unless something like nfarina/homebridge#85 is 
> implemented?

exactly

>set characteristic.eventEnabled = true; (for example in the onRegister callback)

Tried it, but don't know where, almost everywhere without success

**Comment by andig** [comment] 2017-06-26 16:21
>> Are you saying that this update doesn't work unless something like nfarina/homebridge#85 is
implemented?

> exactly

I've verified here https://github.com/nfarina/homebridge/issues/85#issuecomment-310920327 that https://github.com/nfarina/homebridge/issues/85 actually _is_ implemented.

Could you please describe exact steps to reproduce? Are you aware of the fact that this plugin performs _polling_ of the various accessories and that it can take a minute (or the configured interval) before the changes are actually picked up?

**Comment by andig** [comment] 2017-09-03 11:56
ping @jngmrks

**Comment by andig** [comment] 2017-09-22 10:10
Closing due to missing feedback.

**Comment by jngmrks** [comment] 2017-12-09 23:37
Reproduce: Change state of a Switch, wait 1 Minute, open Home App everything ok. Now change the state of a switch or a thermostat, wait 5 Minutes, nothing changes. Close Home App and reopen, state is updated.

**Comment by andig** [comment] 2017-12-10 13:27
@jngmrks could you please also provide a logfile of this behaviour, both the "working" and the "not working" case?

**Comment by jngmrks** [comment] 2017-12-10 15:07
[12/10/2017, 3:02:52 PM] [Fritz!Box] < getSwitchState true
[12/10/2017, 3:03:53 PM] [Fritz!Box] < getSwitchState true
[12/10/2017, 3:04:54 PM] [Fritz!Box] < getSwitchState true
[12/10/2017, 3:05:55 PM] [Fritz!Box] < getSwitchState true

In home app the switch is off. When i close the app and reopen it
the switch is on. Same with all devices.

[12/10/2017, 3:09:19 PM] [Fritz!Box] < getSwitchState true
When i close the app and reopen it - says updating... - its there

**Comment by andig** [comment] 2017-12-10 17:20
Should be fixed in 0.5.10

**Closed as completed** 2017-12-10 17:19 UTC
Labels: bug, information needed
