### ISSUE TITLE
wifi.js TypeError: Cannot read property 'actions'

### ISSUE THREAD

**Issue by robertoschwald** [andig/homebridge-fritz#69] opened 2019-06-28 07:56 UTC
This issue was closed in #47 but is still present.

FB 6490, FritzOS 7.0.2
homebridge-fritz 0.8.0
```
TypeError: Cannot read property 'actions' of undefined
  at FritzWifiAccessory.getOn (/usr/local/lib/node_modules/homebridge-fritz/lib/accessories/wifi.js:96:22)
  at FritzWifiAccessory.update (/usr/local/lib/node_modules/homebridge-fritz/lib/accessories/wifi.js:158:5)
  at ontimeout (timers.js:482:11)
  at tryOnTimeout (timers.js:317:5)
  at Timer.listOnTimeout (timers.js:277:5)
```

**Comment by andig** [comment] 2019-06-28 10:54
Could you add logging inside the tr64 to see why actions isnt defined? I cannot repro this on my fb. Do you have a current firmware?

**Comment by robertoschwald** [comment] 2019-06-28 11:02
FW is current. It's a cable box provided by my ISP, so no chance to get a newer version unless the ISP updates. Current FW on FB 6490 free versions is 7.10 (one version newer than mine, available since end of May '19). 

Some error handling would be great to avoid crashing of homebridge. Is it possible to disable the WLAN checks completely? I don't need it for now, as I'm only interested in my DECT200 sensors. Deactivated homebridge-fritz here for now.

**Comment by robertoschwald** [comment] 2019-06-28 11:05
Will add tr64 logging as soon as my RP 3B+ is up again. Currently its upgrading to Buster.

**Comment by andig** [comment] 2019-07-05 06:56
You could just wifi.display=false but I would appreciate if we could traxk down the root cause as it seems to be reappearing.

**Comment by robertoschwald** [comment] 2019-07-05 08:35
I changed to homebridge-fritz-platform, so I'm afraid I can't help here anymore.

**Comment by andig** [comment] 2019-09-28 10:05
Closing due to missing feedback.

**Closed as completed by andig** 2019-09-28 10:05 UTC
