### ISSUE TITLE
Error GetDeviceList failed

### ISSUE THREAD

**Issue by thschu** [andig/homebridge-fritz#5] opened 2016-09-25 16:54 UTC
Hi,

i the installation works finde, but when im starting Homebridge i get the following error:
`[2016-09-25 18:52:14] [Meine FritzBox] > getDeviceList failed - retrying in 3 seconds
[2016-09-25 18:52:14] [Meine FritzBox] { error: null,
  response: 
   IncomingMessage {
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: false,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: false,
     domain: null,
     _events: 
      { end: [Object],
        close: [Object],
        data: [Function],
        error: [Function] },
     _eventsCount: 4,
     _maxListeners: undefined,
     socket: 
      Socket {
        _connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: null,
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        _bytesDispatched: 123,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     connection: 
      Socket {
        _connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: null,
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        _bytesDispatched: 123,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers: 
      { connection: 'close',
        'content-length': '5103',
        'content-type': 'text/html; charset=utf-8' },
     rawHeaders: 
      [ 'Connection',
        'close',
        'Content-Length',
        '5103',
        'Content-Type',
        'text/html; charset=utf-8' ],
     trailers: {},
     rawTrailers: [],
     upgrade: false,
     url: '',
     method: null,
     statusCode: 404,
     statusMessage: 'Not Found',
     client: 
      Socket {
        _connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: null,
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        _bytesDispatched: 123,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     _consuming: true,
     _dumped: false,
     req: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedHeader: {},
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'GET /webservices/homeautoswitch.lua?0=0&switchcmd=getdevicelistinfos HTTP/1.1\r\nhost: 192.168.178.240\r\nConnection: close\r\n\r\n',
        _headers: [Object],
        _headerNames: [Object],
        _onPendingData: null,
        agent: [Object],
        socketPath: undefined,
        method: 'GET',
        path: '/webservices/homeautoswitch.lua?0=0&switchcmd=getdevicelistinfos',
        _ended: true,
        parser: null,
        res: [Circular] },
     request: 
      Request {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        strictSSL: false,
        callback: [Function],
        readable: true,
        writable: true,
        _qs: [Object],
        _auth: [Object],
        _oauth: [Object],
        _multipart: [Object],
        _redirect: [Object],
        _tunnel: [Object],
        headers: {},
        setHeader: [Function],
        hasHeader: [Function],
        getHeader: [Function],
        removeHeader: [Function],
        method: 'GET',
        localAddress: undefined,
        pool: [Object],
        dests: [],
        __isRequestRequest: true,
        _callback: [Function],
        uri: [Object],
        rejectUnauthorized: false,
        proxy: null,
        tunnel: false,
        setHost: true,
        originalCookieHeader: undefined,
        _disableCookies: true,
        _jar: undefined,
        port: 80,
        host: '192.168.178.240',
        path: '/webservices/homeautoswitch.lua?0=0&switchcmd=getdevicelistinfos',
        httpModule: [Object],
        agentClass: [Object],
        agent: [Object],
        _started: true,
        href: 'http://192.168.178.240/webservices/homeautoswitch.lua?0=0&switchcmd=getdevicelistinfos',
        req: [Object],
        ntick: true,
        response: [Circular],
        originalHost: '192.168.178.240',
        originalHostHeaderName: 'host',
        responseContent: [Circular],
        _destdata: true,
        _ended: true,
        _callbackCalled: true },
     toJSON: [Function: responseToJSON],
     caseless: Caseless { dict: [Object] },
     read: [Function],
     body: '<!DOCTYPE html>\n<html>\n<head>\n<meta http-equiv=content-type content="text/html; charset=utf-8" />\n<meta http-equiv="X-UA-Compatible" content="IE=edge" />\n<meta name="format-detection" content="telephone=no" />\n<meta http-equiv="x-rim-auto-match" content="none" />\n<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, minimal-ui" />\n<meta name="mobile-web-app-capable" content="yes" />\n<meta name="apple-mobile-web-app-capable" content="yes" />\n<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />\n<meta http-equiv="cleartype" content="on">\n<link rel="shortcut icon" href="/css/rd/images/app_icon.png" />\n<link rel="apple-touch-icon" href="/css/rd/images/fritzLogo.svg" />\n<link rel="apple-touch-startup-image" href="/css/rd/images/fritzLogo.svg">\n<link rel="stylesheet" type="text/css" href="/css/rd/singleside_old.css"/>\n<title>FRITZ!Box</title>\n<style type="text/css">\n/********************************************** Allgemein **********************************************/\n@font-face {\nfont-family: \'Source Sans Pro\';\nsrc: url(\'/css/rd/fonts/sourcesanspro.woff\');\n}\n@font-face {\nfont-family: \'Source Sans Pro\';\nsrc: url(\'/css/rd/fonts/sourcesansproBold.woff\');\nfont-weight: bold;\n}\nhtml, input, textarea, keygen, select, button {\nfont-family: \'Source Sans Pro\', Arial, sans-serif;\n}\n* {\n-webkit-tap-highlight-color: rgba(0,0,0,0);\n-webkit-box-sizing: border-box;\n-moz-box-sizing: border-box;\nbox-sizing: border-box;\n-webkit-touch-callout: text;\n-webkit-user-select: text;\n-khtml-user-select: text;\n-moz-user-select: text;\n-ms-user-select: text;\nuser-select: text;\nfont-size: 100%;\nvertical-align: middle;\noutline: 0;\n}\n*:link {\n-webkit-tap-highlight-color: rgba(135,200,250,0.4);\n}\n*::selection {\nbackground: transparent;\n}\n*::-moz-selection {\nbackground: transparent;\n}\n.selectable *::selection {\nbackground: #8fdaff;\n}\n.selectable *::-moz-selection {\nbackground: #8fdaff;\n}\nhtml {\nheight: 100%;\nfont-size: 100%;\nbackground-color: #ececec;\ntransition: background-color 400ms cubic-bezier(0.165, 0.840, 0.440, 1.000);\n}\nbody {\npadding:0;\nmargin:0;\ncolor: #3F464C;\noverflow-x: hidden;\noverflow-y: scroll;\nline-height: 1;\n}\nh1, h2, h3, h4, h5, p, span, div, hr, br, nav, header, section, menu {\nmargin: 0;\npadding: 0;\nborder: 0;\n}\ninput {\nmargin: 0;\npadding: 0;\n}\nhr {\npadding: 0;\nborder-top: 1px solid #d5d5d5;\nmargin: 1rem -1rem;\n}\nheader {\nheight: 3rem;\nwidth: 100%;\nposition: fixed;\ntop: 0;\nleft: 0;\nz-index: 100;\nbackground-color: #006ec0;\ndisplay: -webkit-box;\ndisplay: -moz-box;\ndisplay: -ms-flexbox;\ndisplay: -webkit-flex;\ndisplay: flex;\n-webkit-box-flex-direction: row;\n-moz-box-flex-direction: row;\n-webkit-flex-direction: row;\n-ms-flex-direction: row;\nflex-direction: row;\ntransition: all 400ms cubic-bezier(0.165, 0.840, 0.440, 1.000);\n}\n.hidden {\ndisplay: none;\n}\n.blue_bar_titel {\n-webkit-box-flex: 1 1 auto;\n-moz-box-flex: 1 1 auto;\n-webkit-flex: 1 1 auto;\n-ms-flex: 1 1 auto;\nflex: 1 1 auto;\n-webkit-box-align-self: center;\n-moz-box-align-self: center;\n-webkit-align-self: center;\n-ms-align-self: center;\nalign-self: center;\nmargin: 0.3rem 0 0 0;\nfont-size: 1.65rem;\nfont-weight: bold;\ntext-align: left;\ncolor: #fff;\noverflow: hidden;\nwhite-space: nowrap;\ntext-overflow: ellipsis;\ntext-align: center;\ntransition: all 150ms;\n}\n.blue_bar_titel.fade {\nfont-size: 0;\ncolor: transparent;\n}\n#page_content_no_menu_box {\nmargin-top: 25vh;\nline-height: 1rem;\n}\n#page_content_no_menu_box p {\nmargin: 0.6rem 0;\n}\n@media (min-width: 760px) {\n/*pc*/\n.page_content, .blue_bar_back {\nwidth: 28.5rem;\nmargin: auto;\ntransition: width 400ms cubic-bezier(0.165, 0.840, 0.440, 1.000);\n}\n.forgotPass .page_content {\nwidth: 38.5rem;\n}\n.blue_bar_back {\ntext-align: left;\nheight: 2rem;\nmargin: auto;\nborder: 1px solid #8DA4A3;\nbackground-color: #117ccd;\n}\n.blue_bar_back h2 {\nmargin: 0.45rem 0 0.15rem 1rem;\nfont-weight: bold;\ncolor: #fff;\nletter-spacing: 0.025rem;\n}\n.page_content {\nbackground-color: #f2f0f9;\npadding: 0.5rem;\nborder: 1px solid #8DA4A3;\nborder-top: none;\nmin-height: 5rem;\n}\n}\n@media (max-width: 759px) {\n/*für mobile Ansicht*/\nhtml {\nbackground-color: #fff;\n}\n#page_content_no_menu_box {\nmargin-top: 4.5rem;\nfont-size: 1.25rem;\n}\n.blue_bar_titel {\ntext-align: left;\npadding: 1.1rem 0 1.035rem 0.7rem;\nfont-size: 1.25rem;\nfont-weight: normal;\n}\n.blue_bar_titel.hide {\ncolor: transparent;\n}\n.blue_bar_back {\ndisplay: none;\n}\n}\n@media (min-width: 1900px) {\nhtml {\nfont-size: 125%;\n}\n}\n</style>\n</head>\n<body>\n<div id="main_page_all">\n<header class="" name="" id="blueBarBox">\n<div class="blue_bar_titel" name="" id="blueBarTitel">FRITZ!Box</div>\n</header>\n<div id="page_content_no_menu_box">\n<div class="area_box">\n<div class="blue_bar_back" >\n<div><h2>FRITZ!Box</h2></div>\n</div>\n<div class="page_content">\n<p>Die angegebene URL wurde nicht gefunden. Sie werden auf die Startseite der FRITZ!Box weitergeleitet.</p>\n<p>Falls Sie nicht automatisch auf die Startseite der FRITZ!Box weitergeleitet werden, klicken Sie <a href="/">hier</a>.</p>\n<br>\n</div>\n</div>\n</div>\n</div>\n</body>\n</html>\n' },
  options: { url: 'http://192.168.178.240/webservices/homeautoswitch.lua?0=0&switchcmd=getdevicelistinfos' } }`

The Config is the same from the Example but with my IP and Username/Password.

Fritz OS 06.50 on the Box

**Comment by andig** [comment] 2016-09-26 06:31
This looks funny- as if FB response would not come from api but ui. Could you test if you can call the function from a small script using the smartfritz library?

**Comment by thschu** [comment] 2016-09-26 07:41
Sure i can test it, but with witch small script ? can you post the test case for me ?

**Comment by thschu** [comment] 2016-09-26 07:52
i found this : https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/AVM_Technical_Note_-_Session_ID.pdf

and this

https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/AHA-HTTP-Interface.pdf

Can this help you ?

**Comment by andig** [comment] 2016-09-26 08:29
> i found this

I know these- they are the basis for this library ;)

Please run this- using your own username, password and uri. Script should be placed in your homebridge folder:

```
var fritz = require('smartfritz-promise');

var options = { url:"192.168.178.1" };
fritz.getSessionID("user", "password", options).then(function(sid) {
  console.log(sid);

  // note that the options/url need be carries through every single api call
  fritz.getSwitchList(sid, options).then(function(ains){
    console.log(ains);
  });
});
```

**Comment by thschu** [comment] 2016-09-26 11:37
Hey andig,

this ist the response i get:

`<!DOCTYPE html>
<html lang="de">
    <head>
        <meta http-equiv=content-type content="text/html; charset=utf-8" />
        <meta http-equiv="Cache-Control" content="private, no-transform" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="format-detection" content="telephone=no" />
        <meta http-equiv="x-rim-auto-match" content="none" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <meta http-equiv="cleartype" content="on">
        <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" href="/css/default/images/kopfbalken_links.png" />
        <link rel="apple-touch-startup-image" href="/css/default/images/kopfbalken_links.png">
        <style>
@font-face {
font-family: 'Source Sans Pro';
src: url('/css/rd/fonts/sourcesanspro.woff');
}
@font-face {
font-family: 'Source Sans Pro';
src: url('/css/rd/fonts/sourcesansproBold.woff');
font-weight: bold;
}
@font-face {
font-family: 'AVM';
src: url('/css/rd/fonts/metaWebProBold.woff');
font-weight: bold;
}
html, input, textarea, keygen, select, button {
font-family: 'Source Sans Pro', Arial, sans-serif;
}
.blue_bar_title,
.logoArea {
font-family: 'AVM', 'Source Sans Pro', Arial, sans-serif;
}
</style>
        <link rel='stylesheet' type='text/css' href="/css/rd/login.css"/>
        <title>
FRITZ!Box
</title>
    </head>
    <body>
        <script type="text/javascript">
var gNbc = false;
</script>
        <script src="/js/browser.js"></script>
        <script src="/js/jsl.js"></script>
        <script src="/js/html.js"></script>
        <script src="/js/func.js"></script>
        <script src="/js/html2.js"></script>
        <script src="/js/jxl.js"></script>
        <script src="/js/http.js"></script>
        <script src="/js/md5.js"></script>
        <script type="text/javascript" src="/js/login.js"></script>
        <script type="text/javascript">
var data = {
"firstTenMin": false, 
"challenge": "b9179c50", 
"blockTime": 0, 
"pageTitle": "Willkommen bei Ihrer FRITZ!Box", 
"lastPage": "", 
"loginReason": 0, 
"username": "Thomas", 
"logoutTxt": "\"Sie haben sich erfolgreich von der FRITZ!Box abgemeldet.\"", 
"facTitle": "FRITZ!Box Werkseinstellungen", 
"fromInternet": false, 
"txt": {
  "forgotPassword": "Kennwort vergessen?", 
  "facOnAllowedComp": "Das Wiederherstellen der Werkseinstellungen starten Sie von einem Computer aus, für den die Internetnutzung in der FRITZ!Box unbegrenzt ist.", 
  "pleaseChoose": "Bitte wählen ...", 
  "loginAgainUserMailPass": "Melden Sie sich mit Ihrem Benutzernamen oder Ihrer E-Mail-Adresse und Ihrem Kennwort an.", 
  "facNotSet": "FRITZ!Box wurde nicht auf Werkseinstellungen zurückgesetzt", 
  "notAuthorized": "Sie sind momentan als Benutzer %1%Name%  angemeldet. Dieser Benutzer hat keine Berechtigung, auf die von Ihnen angeforderten FRITZ!Box-Inhalte zuzugreifen.", 
  "autoLogoutLoginAgain": "Sie wurden automatisch abgemeldet, bitte melden Sie sich erneut an.", 
  "sendLoginLink": "Zugangslink senden", 
  "facFailed": "Das Wiederherstellen der Werkseinstellungen ist gescheitert.", 
  "loginAgainUserPass": "Melden Sie sich mit Ihrem Benutzernamen und Ihrem Kennwort an.", 
  "waitMore": "Bitte warten Sie %1 Sekunden.", 
  "facNotAllowed": "Das Wiederherstellen der Werkseinstellungen ist gescheitert, da dieser Computer nicht dazu berechtigt ist.", 
  "autoLogoutTimeout": "Sie wurden automatisch abgemeldet, da seit längerer Zeit keine Aktivität registriert wurde.", 
  "waitOne": "Bitte warten Sie 1 Sekunde.", 
  "chooseUsername": "Bitte geben Sie einen Benutzernamen an.", 
  "sendPushServiceMail": "Push Service Mail senden", 
  "facLoseSettings": "Beachten Sie bitte, dass beim Zurücksetzen alle Ihre Einstellungen verloren gehen!", 
  "mistypedOrNotAuthorized": "Haben Sie sich vielleicht vertippt oder fehlt Ihnen die Zugangsberechtigung für diesen Bereich?", 
  "choose": "OK", 
  "back": "Zurück", 
  "login": "Anmelden", 
  "loginMailSent": "Die E-Mail mit den Zugangsdaten zur Benutzeroberfläche wurde versendet.", 
  "caution": "Achtung", 
  "facRepeat": "Sie können dann die Werkseinstellungen erneut wiederherstellen.", 
  "user": "Benutzername", 
  "pass": "Kennwort", 
  "setFacDefaults": "Werkseinstellungen wiederherstellen", 
  "loginFailed": "Anmeldung fehlgeschlagen.", 
  "loginAgainPass": "Melden Sie sich mit Ihrem Kennwort an.", 
  "tooManyLogins": "Es wurden zu viele Sitzungen gleichzeitig gestartet.", 
  "loginLinkMailPossible": "Wenn Sie Ihr Kennwort für die Benutzeroberfläche vergessen haben, können Sie sich einen Zugangslink per Push Service Mail senden lassen.", 
  "facDisconnectPower": "Trennen Sie die FRITZ!Box kurzzeitig von der Stromversorgung. Nach etwa einer Minute können Sie erneut auf die Benutzeroberfläche zugreifen. Klicken Sie dann auf 'Zur Übersicht'.", 
  "facNotAllowedOr10Min": "Sie haben keine Berechtigung diese Aktion durchzuführen oder Ihre FRITZ!Box ist schon länger als 10 Minuten in Betrieb."
}, 
"cutPowerTxt": "Trennen Sie zunächst die FRITZ!Box kurzzeitig vom Strom und kehren Sie auf diese Seite zurück, nachdem Ihre FRITZ!Box neu gestartet ist.", 
"showUser": true, 
"facWhatNextTxt": "Nach dem Zurücksetzen werden Sie automatisch auf die Übersichtsseite der FRITZ!Box weitergeleitet.", 
"facPationsTxt": "Es kann bis zu 5 Minuten dauern, bis die FRITZ!Box wieder erreichbar ist, bitte haben Sie etwas Geduld.", 
"facIsSetTxt": "Die FRITZ!Box wird auf Werkseinstellungen zurückgesetzt und startet anschließend neu. Alle Verbindungen zur Anlage gehen dabei kurz verloren.", 
"fallbackRedirectUrl": "http:\/\/192.168.178.1\/", 
"ifSetFacTxt": "Wenn Sie Ihr FRITZ!Box-Kennwort vergessen haben, kann die Benutzeroberfläche erst dann wieder geöffnet werden, wenn die FRITZ!Box auf die Werkseinstellungen zurückgesetzt wurde.", 
"setFacTxt": "Alternativ können Sie die FRITZ!Box in die Werkseinstellungen zurücksetzen.", 
"changedPassTxt": "\"Das FRITZ!Box-Kennwort wurde geändert.\"", 
"bluBarTitle": "FRITZ!Box 4020", 
"falseUsername": false, 
"pushmailEnabled": true, 
"activeUsers": [{
    "value": "ftpuser", 
    "txt": "ftpuser"
  }, {
    "value": "Thomas", 
    "txt": "Thomas"
  }]
};
if (gNbc) {
data.nbc = true;
}
function localInit() {
"use strict";
window.history.replaceState({}, '', '/');
html.blueBarHead({
"type": "login",
title: data.bluBarTitle,
parent: document.body
});
login.init(data);
}
localInit();
</script>
    </body>
</html>`

**Comment by andig** [comment] 2016-09-26 12:54
> this ist the response i get:

That's just strange- looks ieke a web page but not an API response.

What do you get if you open this url: `http://fritz.box/webservices/homeautoswitch.lua?0=0&switchcmd=getdevicelistinfos&sid=`

I know it's asking a lot- any chance to send me u/p via pm or do a TeamViewer session?

**Comment by andig** [comment] 2016-10-07 12:48
ping

**Comment by andig** [comment] 2016-10-14 11:54
Closing due to missing feedback.

**Comment by rudibarani** [comment] 2016-11-02 21:35
Hi Andig,
I am having the same issue. Homebridge logs the following:

> [FritzBox] Fritz!Box platform login successful
> [FritzBox] > getDeviceList failed - retrying in 3 seconds

I tried the URL you posted above but only get an empty page with a Fritz!Box Favicon.
My Fritz-Box 7490 is running Fritz!OS 6.6.
Please let me know how I can help you fix this.

**Comment by andig** [comment] 2016-11-02 22:21
Same approach as above- please pm me for access to the box for testing.

**Comment by andig** [comment] 2016-11-06 10:10
@thschu @rudibarani please upgrade to `0.3.2`. I've fixed an error where the plugin would claim "login successful" although login failed. I believe both your problems are caused by invalid login credentials.

**Closed as completed** 2016-11-06 12:52 UTC
Labels: bug
